### ISSUE TITLE
Incompatability with Redis + Sializer (Get returns String)

### ISSUE THREAD

**Issue by kinsi55** [microlinkhq/keyvhq#190] opened 2023-08-28 01:07 UTC
I'm trying to use `@keyvhq/redis` with `sializer` as the De/Serializer. Heres the Keyv options I use:

`{
	store: new (require("@keyvhq/redis"))(REDISURL),
	serialize: sia,
	deserialize: desia
}`

The Problem now lies in the fact that when .get is called, a String will be passed to the deserialize method (https://github.com/microlinkhq/keyvhq/blob/bfe4f4f21da3b1ca7aa798b0f3bd6eea347030fe/packages/core/src/index.js#L59-L63) which in term causes the Desia Method to break.

My current workaround is changing the deserialize method to be this instead:

`x => desia(Buffer.from(x))`

Obviously this isnt super great, and I think a better solution would be having a new option which in term skips the redis > buffer > string conversion and just works with the buffer to begin with (I'm assuming here that thats what happens, I havent looked into it further)

**Edit:** Looks like my workaround doesnt consistently work.

**Comment by Kikobeats** [comment] 2023-08-28 07:23
What's `sializer`?

**Comment by kinsi55** [comment] 2023-08-28 16:50
https://www.npmjs.com/package/sializer / https://github.com/pouya-eghbali/sia

**Comment by Kikobeats** [comment] 2023-08-28 17:03
The contract is clear: `.deserialize` receives whatever you `.serialized` unless [undefined](https://github.com/microlinkhq/keyvhq/blob/bfe4f4f21da3b1ca7aa798b0f3bd6eea347030fe/packages/core/src/index.js#L61)

Since your last sentence was "Looks like my workaround doesnt consistently work" I have to close this although you found a way to reproduce it consistently.

**Closed by Kikobeats** 2023-08-28 17:03 UTC
